package com.progici.languagefever.model.enums;

public enum Stil {
  THE_DIRECT_METHOD,
  THE_GRAMMAR_TRANSLATION_METHOD,
  THE_STRUCTURAL_APPROACH,
  SUGGESTOPEDIA,
  TOTAL_PHYSICAL_RESPONSE,
  COMMUNiCATIVE_LANGUAGE_TEACHING,
  THE_SILENT_WAY,
  THE_NATURAL_APPROACH,
  IMMERSION, 
  THE_LEXICAL_SYLLABUS
}
